### ISSUE TITLE
Performance, Accessibility, Browser Testing

### ISSUE THREAD

**Issue by Lionstein** [Lionstein/animal-rescue-website#1]
https://docs.google.com/spreadsheets/d/18OYuwVJDpmPaagDzblHOcH12vEY0u7v6Kp291lxMXIc/edit?usp=sharing

@charlie-quinn

**Comment by charlie-quinn** [comment]
✅ `This portion of your final assignment has been graded.`

⚠️`Reminder: please close this issue once it has been resolved.`
